# Generated by Django 4.1.1 on 2023-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabgamezzz', '0002_remove_user_collection_giveaway_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='image',
            field=models.URLField(),
        ),
    ]
