# Generated by Django 4.1.1 on 2023-01-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabgamezzz', '0003_alter_giveaway_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='worth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
