# Generated by Django 4.1.1 on 2023-01-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabgamezzz', '0005_alter_giveaway_worth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='worth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
