# Generated by Django 4.1.1 on 2023-01-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabgamezzz', '0006_alter_giveaway_expiry_date_alter_giveaway_worth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lastchecked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
