# Generated by Django 4.1.1 on 2023-01-08 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabgamezzz', '0007_lastchecked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastchecked',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 8)),
        ),
    ]
