# Generated by Django 4.1.1 on 2023-01-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabgamezzz', '0010_alter_lastchecked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='gp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
